#!/usr/bin/perl -w
use DBI;

my $dbh=DBI->connect("DBI:mysql:database=yurnerola;host=localhost","root","123456",{'RaiseError'=>1});

my $sth=$dbh->prepare("select * from hosts");
$sth->execute();
while(my $ref = $sth->fetchrow_hashref()) {
	print "host_id:$ref->{host_id} ";
	print "host_ip:$ref->{host_ip} ";
	print "host_pwd:$ref->{host_pwd} ";
	print "host_addr:$ref->{host_addr}\n";
}

$dbh->disconnect();